SCHEDULING_OBJS = output/myOS/kernel/scheduling/scheduler.o \
				output/myOS/kernel/scheduling/task.o \
				output/myOS/kernel/scheduling/taskQueueFIFO.o \
				output/myOS/kernel/scheduling/FIFO.o \
				output/myOS/kernel/scheduling/RR.o \
				output/myOS/kernel/scheduling/Priority.o \
				output/myOS/kernel/scheduling/taskQueuePriority.o \
				output/myOS/kernel/scheduling/taskVector.o
