# 不需要修改
include myOS/dev/Makefile
include myOS/i386/Makefile
include myOS/lib/Makefile
include myOS/kernel/Makefile

MYOS_OBJS =	output/myOS/start32.o output/myOS/osStart.o \
			${DEV_OBJS} \
			${I386_OBJS} \
			${LIB_OBJS}\
			${KERNEL_OBJS}
