include myOS/dev/Makefile
include myOS/i386/Makefile
include myOS/printk/Makefile
include myOS/lib/Makefile

MYOS_OBJS = output/myOS/start32.o \
            output/myOS/osStart.o \
            ${DEV_OBJS} \
            ${I386_OBJS} \
            ${PRINTK_OBJS} \
            ${LIB_OBJS}
